apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "%%chart-name%%.name" . }}-certs
  labels:
    app: {{ template "%%chart-name%%.name" . }}
    chart: {{ template "%%chart-name%%.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "%%chart-name%%.gen-certs" . ) | indent 2 }}
